/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_selvasai_stt_selvywakeup_WakeUpSolid */

#ifndef _Included_com_selvasai_stt_selvywakeup_WakeUpSolid
#define _Included_com_selvasai_stt_selvywakeup_WakeUpSolid
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_selvasai_stt_selvywakeup_WakeUpSolid
 * Method:    solidInit
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_selvasai_stt_selvywakeup_WakeUpSolid_solidInit
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_selvasai_stt_selvywakeup_WakeUpSolid
 * Method:    solidDetect
 * Signature: (I[S)I
 */
JNIEXPORT jint JNICALL Java_com_selvasai_stt_selvywakeup_WakeUpSolid_solidDetect
  (JNIEnv *, jobject, jint, jshortArray,jintArray);

/*
 * Class:     com_selvasai_stt_selvywakeup_WakeUpSolid
 * Method:    solidDestroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_selvasai_stt_selvywakeup_WakeUpSolid_solidDestroy
  (JNIEnv *, jobject);

/*
 * Class:     com_selvasai_stt_selvywakeup_WakeUpSolid
 * Method:    solidReset
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_selvasai_stt_selvywakeup_WakeUpSolid_solidReset
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
